### ISSUE TITLE
packet delimiter is not added by library

### ISSUE THREAD

**Issue by dwijtsma** [cmcqueen/cobs-python#4]
Hello,

Thanks for making this easy to use cobs library.

I noticed that this library does not add the packet delimiter `b'x\00'` to the end of the package.
Now I have to add the delimiter manually after encoding and have to remove it before I decode.
I think it is a bug, but maybe you did it for a reason unknown to me.

**Comment by dj-foxxy** [comment]
This caught me out. Either it should be added by encode or the documentation and README should say it needs adding.

**Comment by cmcqueen** [comment]
Yes, this is by design, not a bug. The details of how a protocol (or perhaps Flash/EEPROM/disk data storage) uses delimiters may vary. Some might want a delimiter both before and after the data, some just after; some might not want explicit delimiters added, but handle it in a lower-level framing algorithm.

I am happy to update the documentation.
